name: CI

# Runs build and test on:
#   every push that has a change in a file not in the docs folder
#   every pull request with main branch as the base that has a change in a file not in the docs folder
on:
  push:
    paths:
      - '**'
      - '!docs/**'
  pull_request:
    branches:
      - main
    paths:
      - '**'
      - '!docs/**'

jobs:
  build:
    name: Check and build codebase
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get Cache Directory Path
        id: cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Use Cache
        uses: actions/cache@v2
        id: cache
        with:
          path: ${{ steps.cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ matrix.node-version }}-${{ hashFiles('**/yarn.lock') }}

      # install dependencies if cache not found (deps have updated)
      - name: Installation ${{ matrix.node-version }}
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile --non-interactive

      - name: Check Code ${{ matrix.node-version }}
        run: yarn check-ci

      - name: Build Examples ${{ matrix.node-version }}
        run: yarn build-examples

      - name: Build Core ${{ matrix.node-version }}
        run: yarn build
